import { useEffect, useState } from "react";
import { Lightbulb, Sparkles } from "lucide-react";
import { getInsights, getRecommendations, getWaste } from "../services/api";
import { useFilters } from "../context/useFilters";
import { Card, SectionTitle } from "./ui";

export default function InsightsPage() {
  const [insights, setInsights] = useState([]); const [recommendations, setRecommendations] = useState([]); const [waste, setWaste] = useState(null);
  const { filters } = useFilters();
  useEffect(() => { Promise.all([getInsights(filters), getRecommendations(filters), getWaste(filters)]).then(([insightResponse, recommendationResponse, wasteResponse]) => { setInsights(insightResponse.data.items); setRecommendations(recommendationResponse.data.items); setWaste(wasteResponse.data); }).catch(() => {}); }, [filters]);
  return <div className="space-y-6"><SectionTitle eyebrow="Decision support" title="Automated insights" description="Data-driven observations and practical recommendations." /><div className="grid gap-5 lg:grid-cols-2"><Card className="p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#fff0e4] text-cinnamon"><Lightbulb size={19} /></div><h3 className="font-display text-lg font-bold">Business insights</h3></div><div className="space-y-3">{insights.map((insight, index) => <div key={index} className="rounded-2xl bg-[#fff8f1] p-4 text-sm leading-6 text-[#5f5048]">{insight}</div>)}</div></Card><Card className="p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#f0e7d8] text-caramel"><Sparkles size={19} /></div><h3 className="font-display text-lg font-bold">Recommended actions</h3></div><div className="space-y-3">{recommendations.map((recommendation, index) => <div key={index} className="flex gap-3 rounded-2xl border border-[#eadfd3] p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#f5e1d3] text-xs font-bold text-caramel">{index + 1}</span><p className="text-sm leading-6 text-[#5f5048]">{recommendation}</p></div>)}</div></Card></div><Card className="p-5 sm:p-6"><SectionTitle eyebrow="Waste analytics" title="Spoilage and waste" /><div className="rounded-2xl bg-[#fff8f1] p-5">{waste?.available ? <div className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-[#8d7970]">Total waste quantity</p><p className="mt-1 text-2xl font-bold">{waste.total_waste_quantity}</p></div><div><p className="text-xs text-[#8d7970]">Waste value</p><p className="mt-1 text-2xl font-bold">₹{waste.total_waste_amount}</p></div><div><p className="text-xs text-[#8d7970]">Waste percentage</p><p className="mt-1 text-2xl font-bold">{waste.waste_percentage}%</p></div></div> : <p className="text-sm leading-6 text-[#6e5d53]">{waste?.message || "Waste analysis requires waste/spoilage data. Upload additional columns to analyze waste."}</p>}</div></Card></div>;
}
