import { useEffect, useState } from "react";
import { Download, Filter, Search } from "lucide-react";
import { deleteUpload, exportReport, getSales, getUploads } from "../services/api";
import { useFilters } from "../context/useFilters";
import { Card, SectionTitle } from "./ui";

const currency = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 });

export default function SalesPage() {
  const [rows, setRows] = useState([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [uploads, setUploads] = useState([]); const { filters, setFilters } = useFilters();
  useEffect(() => { setLoading(true); getSales({ page, page_size: 15, ...filters }).then((response) => { setRows(response.data.items); setTotal(response.data.total); setLoading(false); }).catch(() => setLoading(false)); }, [page, filters]);
  useEffect(() => { getUploads().then((response) => setUploads(response.data)).catch(() => {}); }, []);
  const pageCount = Math.max(1, Math.ceil(total / 15));
  const applyFilters = (event) => { event.preventDefault(); setFilters((current) => ({ ...current, search })); setPage(1); };
  const exportReportFile = () => exportReport("xlsx", filters).then((response) => { const link = document.createElement("a"); link.href = URL.createObjectURL(response.data); link.download = "floora-sales-report.xlsx"; link.click(); URL.revokeObjectURL(link.href); }).catch(() => {});
  const removeUpload = async (id) => { if (!window.confirm("Delete this upload and all linked sales records?")) return; try { await deleteUpload(id); setUploads((current) => current.filter((upload) => upload.id !== id)); } catch { /* show an error state */ } };
  return <div className="space-y-6"><SectionTitle eyebrow="Sales records" title="Sales data" description="Search, filter, sort, and export your validated records." action={<button className="secondary-button" onClick={exportReportFile}><Download size={16} /> Export report</button>} /><Card className="p-5"><form onSubmit={applyFilters} className="grid gap-3 md:grid-cols-4"><label className="relative"><span className="sr-only">Search</span><Search className="absolute left-3 top-3 text-[#9a897e]" size={16} /><input className="field pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search item or sale ID" /></label><input className="field" type="date" value={filters.start_date || ""} onChange={(event) => setFilters((current) => ({ ...current, start_date: event.target.value || undefined }))} /><input className="field" type="date" value={filters.end_date || ""} onChange={(event) => setFilters((current) => ({ ...current, end_date: event.target.value || undefined }))} /><button className="primary-button"><Filter size={16} /> Apply filters</button></form>{filters.start_date || filters.end_date || filters.search ? <button type="button" onClick={() => { setFilters({}); setSearch(""); setPage(1); }} className="mt-3 text-xs font-semibold text-cinnamon">Clear filters</button> : null}</Card><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left"><thead className="bg-[#fff8f1] text-xs font-bold uppercase tracking-wider text-[#8b776b]"><tr><th className="px-5 py-4">Sale ID</th><th className="px-5 py-4">Item</th><th className="px-5 py-4">Date</th><th className="px-5 py-4">Day</th><th className="px-5 py-4">Price</th><th className="px-5 py-4">Sell time</th></tr></thead><tbody>{loading ? <tr><td colSpan="6" className="p-12 text-center">Loading records…</td></tr> : rows.length ? rows.map((row) => <tr key={row.id} className="border-t border-[#eee4da] text-sm hover:bg-[#fffaf5]"><td className="px-5 py-4 font-mono text-xs text-[#79675d]">{row.sale_id || "—"}</td><td className="px-5 py-4 font-semibold">{row.item_name}</td><td className="px-5 py-4">{row.sales_date}</td><td className="px-5 py-4 text-[#65554c]">{row.day}</td><td className="px-5 py-4 font-bold text-cinnamon">{currency.format(row.price)}</td><td className="px-5 py-4 text-[#65554c]">{row.sell_time || "—"}</td></tr>) : <tr><td colSpan="6" className="p-16 text-center text-sm text-[#8d7970]">No records match these filters.</td></tr>}</tbody></table></div><div className="flex items-center justify-between border-t border-[#eadfd3] p-4 text-xs"><span>{total} records</span><div className="flex items-center gap-2"><button disabled={page === 1} onClick={() => setPage(page - 1)} className="secondary-button px-3 py-2">Previous</button><span>Page {page} of {pageCount}</span><button disabled={page >= pageCount} onClick={() => setPage(page + 1)} className="secondary-button px-3 py-2">Next</button></div></div></Card></div>;
}
