import { useEffect, useState } from "react";
import { Clock3, MoonStar, SunMedium, Sunset } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { getAnalytics } from "../services/api";
import { useFilters } from "../context/useFilters";
import { Card, SectionTitle } from "./ui";

const currency = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const periods = [{name:"Morning",icon:SunMedium,range:"8 AM – 12 PM"},{name:"Afternoon",icon:Sunset,range:"12 PM – 4 PM"},{name:"Evening",icon:Clock3,range:"4 PM – 8 PM"},{name:"Night",icon:MoonStar,range:"8 PM onwards"}];

export default function TimePage() {
  const [analytics, setAnalytics] = useState(null); const [hourData, setHourData] = useState([]);
  useEffect(() => { getAnalytics().then((response) => { setAnalytics(response.data); setHourData(response.data.time_analysis); }).catch(() => {}); }, []);
  const peak = hourData.reduce((best, item) => item.revenue > best.revenue ? item : best, { revenue: -1, label: "—" });
  return <div className="space-y-6"><SectionTitle eyebrow="Time intelligence" title="Sales timing analysis" description="Understand peak periods and demand across the day." /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{periods.map(({name,icon:Icon,range}) => { const period = analytics?.period_analysis?.find((item)=>item.period===name); return <Card key={name} className="p-5"><div className="flex items-center justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#fff0e4] text-cinnamon"><Icon size={19} /></div><span className="text-xs text-[#9a887e]">{range}</span></div><p className="mt-5 text-sm font-semibold">{name}</p><p className="mt-1 text-2xl font-bold">{currency.format(period?.revenue || 0)}</p><p className="mt-1 text-xs text-[#8d7970]">{period?.share.toFixed(1) || 0}% of sales</p></Card>; })}</div><Card className="p-5 sm:p-6"><SectionTitle eyebrow="Hourly demand" title="Sales by hour" /><div className="h-[360px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={hourData}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#eee2d7" /><XAxis dataKey="label" tick={{fontSize:10}} interval={2} /><YAxis tickFormatter={(value)=>currency.format(value)} tick={{fontSize:11}} /><Tooltip formatter={(value)=>currency.format(value)} /><Bar dataKey="revenue" fill="#D86A2E" radius={[5,5,0,0]} /></BarChart></ResponsiveContainer></div></Card><Card className="p-5 sm:p-6"><SectionTitle eyebrow="Peak performance" title="Strongest sales hour" /><div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-[#2d211a] p-5 text-white"><p className="text-xs text-[#c6b2a5]">Peak hour</p><p className="mt-2 text-3xl font-bold">{peak.label}</p><p className="mt-2 text-sm text-[#d4c3b7]">{currency.format(peak.revenue)} revenue</p></div><div className="rounded-2xl bg-[#fff8f1] p-5"><p className="text-xs text-[#8d7970]">Transactions</p><p className="mt-2 text-3xl font-bold">{peak.transactions || 0}</p></div><div className="rounded-2xl bg-[#fff8f1] p-5"><p className="text-xs text-[#8d7970]">Hourly share</p><p className="mt-2 text-3xl font-bold">{analytics?.kpis?.total_sales ? ((peak.revenue/analytics.kpis.total_sales)*100).toFixed(1) : 0}%</p></div></div></Card></div>;
}
